CREATE TABLE veh_iot
(
    COMPACTNESS         INT,
    CIRCULARITY         INT,
    DISTANCE_CIRCULARITY         INT,
    RADIUS_RATIO         INT,
    PR_AXIS_ASPECT_RATIO         INT,
    MAX_LENGTH_ASPECT_RATIO         INT,
    SCATTER_RATIO         INT,
    ELONGATEDNESS         INT,
    PR_AXIS_RECTANGULARITY         INT,
    MAX_LENGTH_RECTANGULARITY         INT,
    SCALED_VARIANCE_MAJOR         INT,
    SCALED_VARIANCE_MINOR         INT,
    SCALED_RADIUS_OF_GYRATION         INT,
    SKEWNESS_ABOUT_MAJOR         INT,
    SKEWNESS_ABOUT_MINOR         INT,
    KURTOSIS_ABOUT_MAJOR         INT,
    KURTOSIS_ABOUT_MINOR         INT,
    HOLLOWS_RATIO         INT,
    Category VARCHAR(100)
);